
// TODO : Member기능에 정의돼있던 상수
const MEMBER_CONST = {
  MEMBER_TEXT: {
    HISTORYBACK_TITLE: '가입을 취소 하시겠습니까?​',
    HISTORYBACK: '입력하신 회원가입 정보가 모두 삭제됩니다.',
    EMAILTITLE: '아이디 입력',
    EMAILPLACEHOLDER: '아이디(이메일)',
    EMP_MAILID_PLACEHOLDER: '이메일 아이디',
    LOGINIDPLACEHOLDER: '아이디 또는 이메일주소',
    ORDERNUMTITLE: '주문번호 입력',
    ORDERNUMPLACEHOLDER: '주문번호',
    PASSTITLE: '비밀번호 입력',
    PASSPLACEHOLDER: '비밀번호',
    PASSCHANGETITLE: '새로운 비밀번호',
    PASSCHANGEPLACEHOLDER: '새 비밀번호 입력',
    PASSCHANGECONFIRMTITLE: '비밀번호 확인',
    PASSCHANGECONFIRMPLACEHOLDER: '새 비밀번호 확인',
    NAMETITLE: '이름 입력',
    NAMEPLACEHOLDER: '이름',
    PHONETITLE: '휴대전화 입력',
    PHONEPLACEHOLDER: '휴대폰 번호(\'-\' 없이 입력)',
    PHONEPLACEHOLDER02: '등록한 휴대폰 번호(\'-\' 없이 입력)',
    PHONEPLACEHOLDER03: '휴대폰번호 입력',
    PHONEAUTHTITLE: '인증번호 4자리',
    PHONEAUTHPLACEHOLDER: '인증번호 4자리',
    EMAIL01: '이메일 형식이 올바르지 않습니다.',
    EMAIL02: '아이디(이메일)를 입력해 주세요.',
    EMAIL03: '휴면계정 아이디(이메일)입니다. 다른 이메일을 입력해 주세요.',
    EMAIL04: '이미 가입된 이메일 주소입니다. 다른 이메일을 입력해 주세요.',
    EMAIL05: ' 아이디(이메일)로 가입된 휴대폰 번호 입니다.<br>신규 가입하실 경우, 휴대폰 인증해 주세요.',
    EMAIL06: '이메일주소 입력',
    EMAIL07: '이메일',
    EMAIL08: '입력하신 이메일로 계정정보를 찾을 수 없습니다.<br>확인 후 다시 이용해 주세요.',
    EMAIL09: '이메일을 입력해 주세요.',
    EMAIL10: '이미 가입된 이메일입니다.<br>다른 이메일을 입력해 주세요.',
    EMAIL11: '연동 할 메일주소를 입력해 주세요.',
    EMAIL12: '가입되지 않은 아이디 입니다. 확인 후 다시 입력해 주세요.',
    EMAIL13: '4~40자 이내로 입력해 주세요.',
    PASS01: '영문 숫자 특수문자 2가지 이상 조합 8~16자',
    PASS02: '비밀번호는 8~16자 이내여야 합니다.',
    PASS03: '비밀번호가 일치하지 않습니다.',
    PASS04: '비밀번호를 입력해 주세요.',
    PASS05: '아이디 또는 비밀번호를 다시 확인해 주세요.',
    PASS06: '비밀번호를 다시 확인해주세요.',
    PASS07: '주문번호 또는 비밀번호를 다시 확인해 주세요.',
    NAME01: '이름을 정확히 입력해 주세요.',
    NAME02: '이름은 두자 이상 입력해주세요.',
    NAME03: '이름은 한글과 영문만 입력 가능합니다.',
    NAME04: '이름을 입력해 주세요.',
    PHONE00: '휴대폰 번호를 입력해 주세요.',
    PHONE01: '입력하신 번호로 인증번호가 발송되었습니다.',
    PHONE02: '인증번호를 다시 한번 확인 후 입력해 주세요.',
    PHONE03: '인증되었습니다. 가입을 진행해 주세요.',
    PHONE04: '이미 인증되었습니다.',
    PHONE05: '인증 번호가 이미 발송되었습니다.\n다시 받으시겠습니까?',
    PHONE06: '인증 번호가 잘못되었습니다.',
    PHONE07: '먼저 전송 버튼을 눌러주세요.',
    PHONE08: '인증번호를 입력해주세요.',
    PHONE09: '인증시간이 초과 되었습니다.\r\n다시한번 전송버튼을 클릭해주세요.',
    PHONE10: '인증번호 입력 시간이 초과하였습니다.<br>다시 시도해 주세요.',
    PHONE11: '인증되었습니다.',
    PHONE12: '휴대폰 번호를 정확하게 입력해 주세요.',
    PHONE13: '휴대폰 번호를 입력해 주세요.',
    AUTHFAILMSG: '인증번호를 다시 한번 확인 후 입력해 주세요.',
    AUTHEMAILBTNNAME: '인증메일 전송',
    AUTHEMAILRESENDBTNNAME: '인증메일 재발송',
    AUTHBTNNAME: '인증번호 전송',
    AUTHRESENDBTNNAME: '인증번호 재발송',
    AUTHSENDNAME01: '전송',
    AUTHSENDNAME02: '재전송',
    AUTHSENDMSG: '인증 번호가 발송 되었습니다.',
    AUTHSENDMSG2: '인증 메일이 발송 되었습니다.',
    AUTHSENDERRMSG: '입력하신 휴대폰 번호로 계정정보를 찾을 수 없습니다.<br>확인 후 다시 이용해 주세요.',
    AUTHSENDERRMSG2: '현재 사용 중인 휴대폰 번호입니다.',
    AUTHSENDERRMSG3: '인증을 해주세요.',
    AUTHEMAILRESENDMSG: '인증메일이 이미 발송되었습니다.\n다시 받으시겠습니까?',
    TVMEMBERMSG: 'TV회원으로 가입된 번호로 본인인증이 필요합니다.<br>통합가입을 원하시면 모바일 회원가입 후 콜센터로 문의해주세요.',
    AGREEAUTHSUCCESS: '약관 동의가 완료됐습니다.',
    BIRTH01: '생년월일',
    BIRTH02: '숫자 8자리 (예: 19840425)',
    BIRTH03: '숫자 8자리로 입력해 주세요.',
    BIRTH04: '숫자만 입력하실 수 있습니다.',
    BIRTH05: '14세 미만은 회원가입이 불가합니다.',
    BIRTH06: '생년월일을 다시 한 번 확인해 주세요.',
    BIRTH07: '성별 및 생년월일을 입력해 주세요.',
    BIRTH08: '생년월일을 입력해 주세요.',
    GENDER01: '성별을 선택해 주세요.',
    ORDERNUM01: '주문번호를 입력해 주세요.',
    ORDERNUM02: '주문번호를 정확히 입력해 주세요.',
    DORMANT_MSG: '휴면계정이 활성화 되었습니다.',
    PASSWORD_CHANGE_SUCCESS: '비밀번호가 변경되었습니다.\n다시 로그인해주세요.',
    MESSAGE_MAXLENGTH_OVER: '자를 초과 할 수 없습니다.'
  },
  WARNING_MESSAGES: {
    SAVE_LATER_TITLE: '선택된 정보가 있습니다.',
    SAVE_LATER: '입력하지 않고 다음에 진행하시겠습니까?',
    SAVE_LATER_NOW: '선택정보 저장',
    NEXT_TIME: '다음에 하기',
    DORMANT_TITLE: '휴면 아이디 재사용',
    DORMANT_MESSAGES: '회원님의 계정은 1년이상 로그인 되지 않아 휴면계정으로 전환되었습니다.\n아래 버튼을 클릭하시면 휴면계정해제 되어 서비스 이용이 가능합니다.',
    DORMANT_BUTTON: '휴면해제하기',
    RE_LOGIN_MESSAGES: '다시 로그인해주세요.',
    NO_MEMBER_RESULT_ERROR01: '고객님의 요청에 의해 삭제된 주문건입니다.\n자세한 문의사항은 고객센터(1688-7700)으로 문의 주세요.',
    NO_MEMBER_RESULT_ERROR02: '주문번호 또는 비밀번호를 다시 확인해 주세요.',
    EMPLOYEER_API_FAIL: '죄송합니다. 인증 메일을 발송하지 못했습니다. 잠시 후 다시 인증요청을 해주시면 감사하겠습니다.',
    SNS_PASSWORD_IS_REGISTERED: '비밀번호가 등록되지 않은 아이디입니다.\nSNS 로그인을 이용해 주세요.'
  },
  SUCCESS_MESSAGES: {
    SAVE: '저장 되었습니다.',
    CHANGE: '정상적으로 변경 되었습니다.',
    AGREE_CHANGE: '수신 설정이 정상적으로 변경되었습니다.'
  },
  ERROR_MESSAGES: {
    SERVER_COMMUNICATION: '서버 통신 오류가 발생했습니다.',
    SERVICE_PROC_ERROR: '서비스 연동중 문제가 발생하였습니다.메인화면으로 이동합니다.',
    SERVICE_PROC_ERROR_COMMON: '일시적인 서비스 장애로 인하여 서비스 이용이 원활하지 않습니다.',
    PROCEDURE_ERROR: '데이터를 불러오는 중 문제가 발생했습니다.\n잠시 후 다시 시도해 주십시오.'
  },
  LOGIN_TYPE: {
    NORMAL: 'K',
    SIMPLE: 'S'
  },
  ROOT_RESULT_MSG: {
    PROCESS_MSG: {
      MODE_A: 'A',
      MODE_P: 'P',
      MODE_E3: 'E3'
    }
  },
  AUTH_RESULT: {
    PROCESS_MSG: {
      SUCCESS: 'S',
      AGE19_ROW: 'F1',
      AUTH_DATA_FALE: 'F2',
      SERVER_ERROR: 'F3'
    }
  },
  EMPLOYEE_MSG: {
    AUTH_FALE: '사내 이메일 인증 후에 특가매장을 이용하실 수 있습니다.'
  },
  SECESSION: '탈퇴회원이거나 NSmall 회원정보를 찾을수 없습니다.'
}

export default MEMBER_CONST
