
// TODO : LNB 에서 쓰이는 상수. (AppAside.vue)
const LNB_CONST = {
  COMPANY_GROUP_CODE: {
    HARIM: 'HARIM',
    HARIMGROUP: 'HARIMGROUP',
    HARIMINC: 'HARIMINC',
    'HARIM-FOODS': 'HARIM-FOODS',
    HARIMPETFOOD: 'HARIMPETFOOD',
    ALLENHARIMLLC: 'ALLENHARIMLLC',
    NSMALL: 'NSMALL'
  }
}

export default LNB_CONST
